### ISSUE TITLE
Potential error

### ISSUE THREAD

**Issue by tpeulen** [Fluorescence-Tools/avtraj#1]
I wonder if you have time to help me, I'm trying to implement your AVtraj code but it throws some errors. I have tried both the avtraj example from the documentation on github and the mdtraj example from the labellib github repository and I haven't been able to get either of them to work. I'm running python 3.7 which may be part of the problem, although I see that you have amended the code for migration to python 3 and further to our earlier exchange I presume that you ordinarily have no issues with running AVtraj in 3.7. 
When I load an xtc file and the corresponding topology pdb the loader works correctly.
Making a dictionary to specify the attachment site works correctly. I've called them avpd and avpd2
However,  when I run 

```
av_traj_1 = avt.AVTrajectory(traj, '!103', avpd)
print(len(av_traj_1))
print(av_traj_1)
av_traj_2 = avt.AVTrajectory(traj, 'V353', avpd2)
print(len(av_traj_2))
print(av_traj_2)
```

 I get the following error
```

    av_traj_1 = avt.AVTrajectory(traj, '!103', avpd)

  File "C:\Users\fbsmawadmin\Anaconda3\lib\site-packages\avtraj\__init__.py", line 800, in __init__
    string.lower(

AttributeError: module 'string' has no attribute 'lower'
```

which leads me to the third line of this block of code in the init.py file

```
        selection = ""
        selection += "chainid " + av_functions.LETTERS[
            string.lower(
                av_parameters['chain_identifier']
            )
        ]
        selection += " and residue " + str(av_parameters['residue_seq_number'])
        selection += " and name " + str(av_parameters['atom_name'])
        self.attachment_atom_index = self.trajectory.topology.select(selection)[0]
```

can you tell me what I'm missing?

**Comment by tpeulen** [comment]
This bug is related to the changed behavior of Python 3 when treating strings. In python 3 the module string has no function ``lower``anymore. Instead, lower is now a method of the string.

**Comment by Mattyboi123** [comment]
I have uninstalled the old version of AVtraj that I had and installed the updated version. However attempting to run the example script on a short MDtrajectory threw an error in LabelLib. I checked the last updates of Labellib and saw that they had occurred around the time of the changes to AVtraj. Thus, I uninstalled Labellib and installed the updated version. I first tested this new installation of Labellib in pyMOL as I had previously had this functionality working nicely. However it now throws an error as below.

File "C:\Users\fbsmawadmin\Anaconda3\Lib\site-packages\LabelLib\FlexLabel\python\LabelLib_pymol.py", line 41, in genAV
    m=avToModel(av1)
  File "C:\Users\fbsmawadmin\Anaconda3\Lib\site-packages\LabelLib\FlexLabel\python\LabelLib_pymol.py", line 89, in avToModel
    points = av.points()
AttributeError: 'LabelLib.Grid3D' object has no attribute 'points'

I looked in the labellib_pymol.py script and could find no mention of 'Grid3D', I also couldn't find this object in the other .py files that came with LabelLib. Additionally, upon following the conda installation described on the github repository, one only ends up with the egg files for LabelLib and one still has to manually download the zip archive for LabelLib and then add the LabelLib folder to the python environment - is this how it should be?  Iwas surprised that the conda install didn't in fact install the files (python scripts) that make up the package, I wondered if this might be the source of the error?

**Comment by tpeulen** [comment]
This error is related to the latest enhancement of labelib (see https://github.com/Fluorescence-Tools/LabelLib/issues/10). I am not sure if this enhancement, as it is very small, got a new version number. Hence, `conda` may install labellib from your local cache.

Make sure, that you purge your cache by

```
conda clean --all
```

Next, install the library.

```
conda create -n test_env -c tpeulen -c conda-forge labellib avtraj
```

activate the test environment

```
conda activate test_env
```

After you did that, everything that is covered by the test cases in the `test`folder should work.

**Comment by Mattyboi123** [comment]
having removed any trace of labellib or avtraj from my laptop and cleaned
the cache, following this set of instructions returns a list of conflicts,
failed

UnsatisfiableError: The following specifications were found to be
incompatible with each other:



Package numpy conflicts for:
avtraj -> numpy
labellib ->
numpy[version='>=1.11.3,<2.0a0|>=1.15.4,<2.0a0|>=1.16.0,<2.0a0|>=1.17.1,<2.0a0|>=1.17.2,<2.0a0']
Package vs2015_runtime conflicts for:
labellib -> vs2015_runtime
Package pyyaml conflicts for:
avtraj -> pyyaml
Package python conflicts for:
avtraj -> python[version='>=3.7,<3.8.0a0']
labellib -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package labellib conflicts for:
avtraj -> labellib
Package vc conflicts for:
labellib -> vc[version='9.*|>=14.1,<15.0a0']
Package mdtraj conflicts for:
avtraj -> mdtraj
Package numba conflicts for:
avtraj -> numba

I notice a few mentions of 2.7 in the list such as next to labellib, but
its not clear why they are there as I have previously scrubbed anaconda
altogether and reinstalled it with 3.7 fairly recently. Im also confused as
to what the test environment accomplishes if it doesn't create an
environment that is isolated and hence allows parallel versions of hings to
be installed without provoking conflicts?

Matt

**Comment by Mattyboi123** [comment]
am I missing something in general about how github works? installing avtraj
via conda or by downloading the tarball, installs the egg info and the
scripts but labellib it only instals ithe egg info and then one still need
to manually clone the files from github and add them into the python
environment and labellib still seems to insist on using python 2.7 rather
than 3.7 which makes it conflict with avraj rather than being callable from
it. Is there something pending in how the various files are connected and
collated i nth repository or am I being an idiot?

**Comment by tpeulen** [comment]
Tank you a lot for reporting this problem. This conflict did neither show up on the continuous integration nor my local build environment. However, I was able to reproduce your problem. 

In principle, everything in conda should work out of the box. I hope I fixed your problem and you can install the software as described above. 

> This error is related to the latest enhancement of labelib (see Fluorescence-Tools/LabelLib#10). I am not sure if this enhancement, as it is very small, got a new version number. Hence, conda may install labellib from your local cache.
> 
> Make sure, that you purge your cache by
> 
> conda clean --all
> 
> Next, install the library.
> 
> conda create -n test_env -c tpeulen -c conda-forge labellib avtraj
> 
> activate the test environment
> 
> conda activate test_env
> 
> After you did that, everything that is covered by the test cases in the testfolder should work.
>

**Comment by Mattyboi123** [comment]
HI Thomas,

Labellib still doesn't install the actual files when installed with conda,
only the egg info folder. Also the version is 2018_12_12 whereas the
tarball version on git has a newer date reflecting the recent changes.
Even so, manually downloading the zip archive for LabelLib and putting the
folder in the python path no longer gives the in-pymol functionality that I
previously had working and now returns the error

Traceback (most recent call last):
  File "C:\Users\fbsmawadmin\Anaconda3\Lib\site-packages\LabelLib\FlexLabel\python\LabelLib_pymol.py",
line 41, in genAV
    m=avToModel(av1)
  File "C:\Users\fbsmawadmin\Anaconda3\Lib\site-packages\LabelLib\FlexLabel\python\LabelLib_pymol.py",
line 89, in avToModel
    points = av.points()
AttributeError: 'LabelLib.Grid3D' object has no attribute 'points'


but is this about the version of LabelLib that is in fact available not
being the most up to date one ?


Trying to follow the test env conda-forge instructions also exhibits this
curious issue of only installing the egg info folder and not the actual
Labellib folders??


I also checked that I had the most up to date version of conda installed
with conda update --all, retried both the test environment and my base
environment installs and still had the LAbellib Grid3d no atttribute points
error



The same LabelLib issue of lacking the attribute points is returned upon
attempting to run the avtraj script.


Would you recommend unistalling conda entirely, reinstalling it and
following the test env conda forge installation? Is this likely to mean
that all of the files and folders acrually get installed rather than only
the egg info folder??


I am sorry to be flagging this up as a thorn in your side!


Cheers

Matt

**Comment by Mattyboi123** [comment]
additionally, he md_traj example throws another error relating to LabelLib


  File "<ipython-input-1-5a63e663ffbc>", line 1, in <module>

runfile('C:/Users/fbsmawadmin/Anaconda3/Lib/site-packages/LabelLib/FlexLabel/python/mdtraj_example.py',
wdir='C:/Users/fbsmawadmin/Anaconda3/Lib/site-packages/LabelLib/FlexLabel/python')

  File
"C:\Users\fbsmawadmin\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 827, in runfile
    execfile(filename, namespace)

  File
"C:\Users\fbsmawadmin\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File
"C:/Users/fbsmawadmin/Anaconda3/Lib/site-packages/LabelLib/FlexLabel/python/mdtraj_example.py",
line 80, in <module>
    sys.exit(main(sys.argv[1:]))

  File
"C:/Users/fbsmawadmin/Anaconda3/Lib/site-packages/LabelLib/FlexLabel/python/mdtraj_example.py",
line 38, in main
    distances=ll.sampleDistanceDistInv(gridDonor,gridAcceptor,1000000)

AttributeError: module 'LabelLib' has no attribute 'sampleDistanceDistInv'

**Comment by Mattyboi123** [comment]
HI guys, just to let you know that the code is all working fine now (after a complete scouring of Anaconda and reinstall). I have a new question - how should one select a site for labelling in the mdtraj script in the case where the macromolecule has more than one chain?

Cheers
Matt
